export const quizData = [
  {
    question: "What is the capital of France?",
    a: "Berlin",
    b: "Madrid",
    c: "Paris",
    d: "Rome",
    correct: "c",
  },
  {
    question: "Which language is used for web development?",
    a: "Python",
    b: "JavaScript",
    c: "C++",
    d: "Java",
    correct: "b",
  },
  {
    question: "Which planet is known as the Red Planet?",
    a: "Earth",
    b: "Mars",
    c: "Jupiter",
    d: "Saturn",
    correct: "b",
  },
  {
    question: "Who wrote 'Harry Potter'?",
    a: "J.R.R. Tolkien",
    b: "George R.R. Martin",
    c: "J.K. Rowling",
    d: "Suzanne Collins",
    correct: "c",
  },
  {
    question: "What is the square root of 64?",
    a: "6",
    b: "7",
    c: "8",
    d: "9",
    correct: "c",
  },
];
